#!/usr/bin/env sh
if pgrep "pavucontrol";
    then 
        swaymsg [app_id="pavucontrol"] scratchpad show, resize set width 80 ppt height  70 ppt
    else
        pavucontrol && swaymsg [app_id="pavucontrol"] scratchpad show, resize set width 80 ppt height  70 ppt
fi